substitutions:
  
external_components:
  - source:
      type: local
      path: C:/Users/Tommy/Downloads/Satelite1/esphome/components
      
    components:
        - audio 
        - fusb302b
        - i2s_audio
        - memory_flasher
        - microphone
        - micro_wake_word
        - mixer
        - pcm5122
        - psram 
        - resampler 
        - satellite1 
        - snapcast
        - speaker
        - tas2780
        - voice_assistant 

